### ISSUE TITLE
Setting up the project (Kanban board)

### ISSUE THREAD

**Issue by Mofuhidy** [Mofuhidy/space-travelers--hub#25]
https://github.com/Mofuhidy/space-travelers--hub/projects/1

We are Two @Mofuhidy & @tjay1760

**Comment by bobb-Rob** [comment]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Mofuhidy & @tjay1760,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ Equal distribution of work
✅ Project cards set up correctly
✅ Very descriptive project cards

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

**Comment by Mofuhidy** [comment]
Thank you very much @bobb-Rob  😄
